version: '3.4'

services:
  prss.rmqpublisher.infra.http.daemon:
    image: prssrmqpublisherinfrahttpdaemon:dev
    container_name: rmq-publisher-http
    build:
      context: ./src/RmqPublisher/Publication.Rabbit.Subscription.Storage.RmqPublisher.Infra.Http.Daemon
      dockerfile: Dockerfile
    ports:
      - "5047:5047"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5047"
      RABBIT_MQ_CONNECTION_STRING: "amqp://guest:guest@rabbit-mq:5672"
      AUTH_TOKEN: "784aae1c1abb4aa3914f42a81e893ed2"
    restart: always
    
    
  prss.rmqsubscriber.infra.dtt.daemon:
    image: prssrmqsubscriberinfradttdaemon:dev
    container_name: rmq-subscriber-dtt
    build:
      context: ./src/RmqSubscriber/Publication.Rabbit.Subscription.Storage.RmqSubscriber.Infra.Dtt.Daemon
      dockerfile: Dockerfile
    ports:
      - "5048:5048"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:5048"
      RABBIT_MQ_CONNECTION_STRING: "amqp://guest:guest@rabbit-mq:5672"
    restart: always


  rabbit.mq.service:
    image: rabbitmq:3
    container_name: rabbit-mq
    ports: 
      - "4672:5672"
      - "4671:5671"
      - "3369:4369"
      - "24672:25672"
      - "14692:15692"
      - "14691:15691"
    restart: always